apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://git.deimos.co.za/mensaah/gitOps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
